name = "commons-thermometer"
main = "src/index.js"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]


# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
# crons = ["* * * *"] # run every minute
crons = ["*/5 14-04 * * *"]

# */30 05-13 * * *	Every 30 minutes, between 05:00 AM and 01:59 PM	Tue, 19 Mar 2024 05:00:00
# */5 14-04 * * *	Every 5 minutes, between 02:00 PM and 04:59 AM	Mon, 18 Mar 2024 16:10:00


[vars]
BOT_ID = "B06PX5XM24C"
BOT_USER = "U06PE5CJP63"

[observability.logs]
enabled = true
